name: MultiPermissions
version: '1.0'
main: nl.multitime.multiPermissions.MultiPermissions
api-version: '1.20'
authors: [ MultiTime ]
description: Minecraft Client Made by Multtime himself
website: #SOON
